-- Table: rs41_header
-- Purpose: Stores comprehensive header metadata for GRUAN RS41 radiosonde observations
-- Description: Contains detailed instrument metadata, station information, processing history,
--              and quality control data for Vaisala RS41 radiosondes in the GRUAN network

DROP TABLE IF EXISTS rs41_header CASCADE;

CREATE TABLE rs41_header
(
    report_id                                        serial,
    comment                                          character varying(255),
    conventions                                      character varying(255),
    g_file_comment                                   character varying(255),
    g_file_timestamp                                 character varying(255),
    g_file_type                                      character varying(255),
    g_file_typename                                  character varying(255),
    g_file_typeversion                               character varying(255),
    g_groundcheck_list                               character varying(255),
    g_groundcheck_ri41_altitude                      character varying(255),
    g_groundcheck_ri41_available                     character varying(255),
    g_groundcheck_ri41_checkdate                     character varying(255),
    g_groundcheck_ri41_checklength                   character varying(255),
    g_groundcheck_ri41_checktype                     character varying(255),
    g_groundcheck_ri41_offsetaltituderefpressure     character varying(255),
    g_groundcheck_ri41_offsetpressure                character varying(255),
    g_groundcheck_ri41_pressureqc                    character varying(255),
    g_groundcheck_ri41_refpressure                   character varying(255),
    g_groundcheck_ri41_sensorpressure                character varying(255),
    g_groundcheck_shc_altitude                       character varying(255),
    g_groundcheck_shc_analysed                       character varying(255),
    g_groundcheck_shc_autodetected                   character varying(255),
    g_groundcheck_shc_available                      character varying(255),
    g_groundcheck_shc_checkdate                      character varying(255),
    g_groundcheck_shc_checklength                    character varying(255),
    g_groundcheck_shc_checktype                      character varying(255),
    g_groundcheck_shc_offsetaltituderefpressure      character varying(255),
    g_groundcheck_shc_offsetpressure                 character varying(255),
    g_groundcheck_shc_offsetpressureuc               character varying(255),
    g_groundcheck_shc_offsetrelativehumidity         character varying(255),
    g_groundcheck_shc_offsetrelativehumidityuc       character varying(255),
    g_groundcheck_shc_offsettemperature              character varying(255),
    g_groundcheck_shc_offsettemperatureuc            character varying(255),
    g_groundcheck_shc_pressureqc                     character varying(255),
    g_groundcheck_shc_refpressure                    character varying(255),
    g_groundcheck_shc_refpressurecount               character varying(255),
    g_groundcheck_shc_refpressurelinslope            character varying(255),
    g_groundcheck_shc_refpressurestddev              character varying(255),
    g_groundcheck_shc_refpressureuc                  character varying(255),
    g_groundcheck_shc_refpressureucfinal             character varying(255),
    g_groundcheck_shc_refrelativehumidity            character varying(255),
    g_groundcheck_shc_refrelativehumiditycount       character varying(255),
    g_groundcheck_shc_refrelativehumiditylinslope    character varying(255),
    g_groundcheck_shc_refrelativehumiditystddev      character varying(255),
    g_groundcheck_shc_refrelativehumidityuc          character varying(255),
    g_groundcheck_shc_refrelativehumidityucfinal     character varying(255),
    g_groundcheck_shc_reftemperature                 character varying(255),
    g_groundcheck_shc_reftemperaturecount            character varying(255),
    g_groundcheck_shc_reftemperaturelinslope         character varying(255),
    g_groundcheck_shc_reftemperaturestddev           character varying(255),
    g_groundcheck_shc_reftemperatureuc               character varying(255),
    g_groundcheck_shc_reftemperatureucfinal          character varying(255),
    g_groundcheck_shc_relativehumidityqc             character varying(255),
    g_groundcheck_shc_relativehumiditysensorsdiff    character varying(255),
    g_groundcheck_shc_relativehumiditysensorsqc      character varying(255),
    g_groundcheck_shc_sensorpressure                 character varying(255),
    g_groundcheck_shc_sensorpressurecount            character varying(255),
    g_groundcheck_shc_sensorpressurelinslope         character varying(255),
    g_groundcheck_shc_sensorpressurestddev           character varying(255),
    g_groundcheck_shc_sensorpressureuc               character varying(255),
    g_groundcheck_shc_sensorpressureucfinal          character varying(255),
    g_groundcheck_shc_sensorrelativehumidity         character varying(255),
    g_groundcheck_shc_sensorrelativehumiditycount    character varying(255),
    g_groundcheck_shc_sensorrelativehumiditylinslope character varying(255),
    g_groundcheck_shc_sensorrelativehumiditystddev   character varying(255),
    g_groundcheck_shc_sensorrelativehumidityuc       character varying(255),
    g_groundcheck_shc_sensorrelativehumidityucfinal  character varying(255),
    g_groundcheck_shc_sensortemperature              character varying(255),
    g_groundcheck_shc_sensortemperaturecount         character varying(255),
    g_groundcheck_shc_sensortemperaturelinslope      character varying(255),
    g_groundcheck_shc_sensortemperaturestddev        character varying(255),
    g_groundcheck_shc_sensortemperatureuc            character varying(255),
    g_groundcheck_shc_sensortemperatureucfinal       character varying(255),
    g_groundcheck_shc_temperatureqc                  character varying(255),
    g_groundcheck_shelter_available                  character varying(255),
    g_groundsystem_id                                character varying(255),
    g_groundsystem_internalkey                       character varying(255),
    g_groundsystem_manufacturer                      character varying(255),
    g_groundsystem_model                             character varying(255),
    g_groundsystem_modelfamily                       character varying(255),
    g_groundsystem_name                              character varying(255),
    g_groundsystem_serialnumber                      character varying(255),
    g_groundsystem_software                          character varying(255),
    g_groundsystem_type                              character varying(255),
    g_mainsonde_manufacturer                         character varying(255),
    g_mainsonde_model                                character varying(255),
    g_mainsonde_modelfamily                          character varying(255),
    g_mainsonde_name                                 character varying(255),
    g_mainsonde_serialnumber                         character varying(255),
    g_mainsonde_type                                 character varying(255),
    g_measurement_astronomicaltwilightcount          character varying(255),
    g_measurement_balloon                            character varying(255),
    g_measurement_balloonnumber                      character varying(255),
    g_measurement_burstpointaltitude                 character varying(255),
    g_measurement_burstpointdatetime                 character varying(255),
    g_measurement_burstpointgeopotheight             character varying(255),
    g_measurement_burstpointpressure                 character varying(255),
    g_measurement_burstpointsource                   character varying(255),
    g_measurement_burstpointtime                     character varying(255),
    g_measurement_civiltwilightcount                 character varying(255),
    g_measurement_daytimecount                       character varying(255),
    g_measurement_equipment                          text,
    g_measurement_fillingweight                      character varying(255),
    g_measurement_fullstringlength                   character varying(255),
    g_measurement_grossweight                        character varying(255),
    g_measurement_id                                 character varying(255),
    g_measurement_internalkey                        character varying(255),
    g_measurement_lastchange                         character varying(255),
    g_measurement_locgpsaltitudegeoid                character varying(255),
    g_measurement_locgpsaltitudemean                 character varying(255),
    g_measurement_locgpsaltitudeoffset               character varying(255),
    g_measurement_locgpsaltituderef                  character varying(255),
    g_measurement_locgpsaltituderesidual             character varying(255),
    g_measurement_nauticaltwilightcount              character varying(255),
    g_measurement_nighttimecount                     character varying(255),
    g_measurement_parachute                          character varying(255),
    g_measurement_partlyvisiblesuncount              character varying(255),
    g_measurement_payload                            character varying(255),
    g_measurement_positionrangelatnorth              character varying(255),
    g_measurement_positionrangelatsouth              character varying(255),
    g_measurement_positionrangeloneast               character varying(255),
    g_measurement_positionrangelonwest               character varying(255),
    g_measurement_precipitablewatercolumn            character varying(255),
    g_measurement_precipitablewatercolumnuc          character varying(255),
    g_measurement_rig                                character varying(255),
    g_measurement_standardtime                       timestamp with time zone,
    g_measurement_starttime                          character varying(255),
    g_measurement_starttimediff                      character varying(255),
    g_measurement_starttimemanufacturer              character varying(255),
    g_measurement_starttimesource                    character varying(255),
    g_measurement_timeofday                          character varying(255),
    g_measurement_tropopausealtitude                 character varying(255),
    g_measurement_tropopausedatetime                 character varying(255),
    g_measurement_tropopausedetected                 character varying(255),
    g_measurement_tropopausegeopotheight             character varying(255),
    g_measurement_tropopausepottemperature           character varying(255),
    g_measurement_tropopausepressure                 character varying(255),
    g_measurement_tropopausetemperature              character varying(255),
    g_measurement_tropopausetime                     character varying(255),
    g_measurement_twilightcount                      character varying(255),
    g_measurement_unwinder                           character varying(255),
    g_measurement_version                            character varying(255),
    g_measurementsetup_id                            character varying(255),
    g_measurementsetup_key                           character varying(255),
    g_measurementsetup_name                          character varying(255),
    g_measurementsetup_type                          character varying(255),
    g_measurementsystem_altitude                     character varying(255),
    g_measurementsystem_id                           character varying(255),
    g_measurementsystem_key                          character varying(255),
    g_measurementsystem_latitude                     character varying(255),
    g_measurementsystem_longitude                    character varying(255),
    g_measurementsystem_name                         character varying(255),
    g_measurementsystem_operatedby                   character varying(255),
    g_measurementsystem_type                         character varying(255),
    g_measurementsystem_wigossid                     character varying(255),
    g_measurementsystem_wmocode                      character varying(255),
    g_measurementsystem_wmoname                      character varying(255),
    g_measurementsystem_wmoregion                    character varying(255),
    g_product_ascentincluded                         character varying(255),
    g_product_descentincluded                        character varying(255),
    g_product_fullkey                                character varying(255),
    g_product_history                                character varying(255),
    g_product_id                                     character varying(255),
    g_product_key                                    character varying(255),
    g_product_level                                  character varying(255),
    g_product_leveldescription                       character varying(255),
    g_product_name                                   character varying(255),
    g_product_postflightincluded                     character varying(255),
    g_product_prelaunchincluded                      character varying(255),
    g_product_processingsteps                        text,
    g_product_producer                               character varying(255),
    g_product_producercontact                        character varying(255),
    g_product_producertool                           character varying(255),
    g_product_references                             character varying(255),
    g_product_revision                               character varying(255),
    g_product_status                                 character varying(255),
    g_product_statusdescription                      character varying(255),
    g_product_timeresolution                         character varying(255),
    g_product_title                                  character varying(255),
    g_product_version                                character varying(255),
    g_site_altitude                                  character varying(255),
    g_site_climate                                   character varying(255),
    g_site_country                                   character varying(255),
    g_site_district                                  character varying(255),
    g_site_environmenttype                           character varying(255),
    g_site_id                                        character varying(255),
    g_site_institution                               character varying(255),
    g_site_iscooperation                             character varying(255),
    g_site_isdistributed                             character varying(255),
    g_site_ismobile                                  character varying(255),
    g_site_key                                       character varying(255),
    g_site_landuse                                   character varying(255),
    g_site_latitude                                  character varying(255),
    g_site_longitude                                 character varying(255),
    g_site_name                                      character varying(255),
    g_site_population                                character varying(255),
    g_site_surfaceroughness                          character varying(255),
    g_site_timezone                                  character varying(255),
    g_site_topography                                character varying(255),
    g_surfaceobs_cloudstext                          character varying(255),
    g_surfaceobs_comment                             character varying(255),
    g_surfaceobs_pressure                            character varying(255),
    g_surfaceobs_relativehumidity                    character varying(255),
    g_surfaceobs_synopclouds                         character varying(255),
    g_surfaceobs_temperature                         character varying(255),
    g_surfaceobs_winddirection                       character varying(255),
    g_surfaceobs_windspeed                           character varying(255),
    g_telemetrysonde_manufacturer                    character varying(255),
    g_telemetrysonde_model                           character varying(255),
    g_telemetrysonde_modelfamily                     character varying(255),
    g_telemetrysonde_name                            character varying(255),
    g_telemetrysonde_serialnumber                    character varying(255),
    g_telemetrysonde_type                            character varying(255),
    g_telemetrysonde_xdata                           character varying(255),
    g_telemetrysonde_xdatasensors                    character varying(255),
    history                                          character varying(255),
    institution                                      character varying(255),
    "references"                                     character varying(255),
    source                                           character varying(255),
    title                                            character varying(255),
    idstation_pk                                     int
);

-- Table: rs41_data
-- Purpose: Stores atmospheric measurement data from GRUAN RS41 radiosonde observations
-- Description: Contains comprehensive vertical profiles of temperature, humidity, pressure,
--              wind, and position data with detailed uncertainty estimates for each variable

DROP TABLE IF EXISTS rs41_data CASCADE;

CREATE TABLE rs41_data
(
    observation_id             serial,
    alt                        real,
    alt_amsl                   real,
    alt_amsl_uc                real,
    alt_amsl_uc_tcor           real,
    alt_amsl_uc_ucor           real,
    alt_gph                    real,
    alt_gph_uc                 real,
    alt_gph_uc_tcor            real,
    alt_gph_uc_ucor            real,
    alt_raw                    real,
    alt_raw_flags              real,
    alt_uc                     real,
    alt_wgs84                  real,
    alt_wgs84_uc               real,
    alt_wgs84_uc_tcor          real,
    alt_wgs84_uc_ucor          real,
    band                       real,
    ciwv                       real,
    ciwv_uc                    real,
    dorn                       real,
    dp                         real,
    dp_uc                      real,
    dp_uc_scor                 real,
    dp_uc_tcor                 real,
    dp_uc_ucor                 real,
    geoid                      real,
    grav                       real,
    hca                        real,
    hdop_raw                   real,
    icesat                     real,
    ihum_raw                   real,
    ihum_raw_flags             real,
    lat                        double precision,
    lat_raw                    double precision,
    lat_raw_flags              real,
    lat_sm                     double precision,
    lat_uc                     real,
    lat_uc_tcor                real,
    lat_uc_ucor                real,
    latmf                      double precision,
    lon                        double precision,
    lon_raw                    double precision,
    lon_raw_flags              real,
    lon_sm                     double precision,
    lon_uc                     real,
    lon_uc_tcor                real,
    lon_uc_ucor                real,
    lonmf                      double precision,
    penper                     real,
    penrad                     real,
    penrad_uc                  real,
    penrad_uc_ucor             real,
    penspeed                   real,
    penspeed_uc                real,
    penspeed_uc_ucor           real,
    posx_raw                   double precision,
    posx_raw_flags             real,
    posy_raw                   double precision,
    posy_raw_flags             real,
    posz_raw                   double precision,
    posz_raw_flags             real,
    press                      real,
    press_gnss                 real,
    press_gnss_uc              real,
    press_gnss_uc_tcor         real,
    press_gnss_uc_ucor         real,
    press_sens                 real,
    press_sens_corr            real,
    press_sens_corr_cal        real,
    press_sens_corr_sm         real,
    press_sens_raw             real,
    press_sens_raw_flags       real,
    press_sens_uc              real,
    press_sens_uc_tcor         real,
    press_sens_uc_tcor_cal     real,
    press_sens_uc_ucor         real,
    press_sens_uc_ucor_sm      real,
    press_uc                   real,
    rh                         real,
    rh_corr                    real,
    rh_corr_sm                 real,
    rh_corr_tl                 real,
    rh_corr_trc                real,
    rh_raw                     real,
    rh_raw_flags               real,
    rh_res                     real,
    rh_uc                      real,
    rh_uc_tcor                 real,
    rh_uc_tcor_cal             real,
    rh_uc_tcor_tint            real,
    rh_uc_tcor_tlc             real,
    rh_uc_tlc                  real,
    rh_uc_ucor                 real,
    rh_uc_ucor_sm              real,
    rh_uc_ucor_tair            real,
    rh_uc_ucor_tlc             real,
    saa                        real,
    sea                        real,
    swdif                      real,
    swdif_uc                   real,
    swdif_uc_scor              real,
    swdir                      real,
    swdir_uc                   real,
    swdir_uc_scor              real,
    sza                        real,
    tau_rh                     real,
    tau_rh_uc                  real,
    tau_rh_uc_tcor             real,
    temp                       real,
    temp_corr                  real,
    temp_corr_rad              real,
    temp_corr_sm               real,
    temp_raw                   real,
    temp_raw_flags             real,
    temp_res                   real,
    temp_uc                    real,
    temp_uc_rad                real,
    temp_uc_scor               real,
    temp_uc_scor_rad           real,
    temp_uc_tcor               real,
    temp_uc_tcor_cal           real,
    temp_uc_tcor_rad           real,
    temp_uc_ucor               real,
    temp_uc_ucor_rad           real,
    temp_uc_ucor_sm            real,
    thum_raw                   real,
    thum_raw_flags             real,
    time                       real,
    vdop_raw                   real,
    vent                       real,
    vent_uc                    real,
    vent_uc_ucor               real,
    vspeed                     real,
    vspeed_uc                  real,
    vspeed_uc_ucor             real,
    wdir                       real,
    wdir_corr_sm               real,
    wdir_uc                    real,
    wdir_uc_ucor               real,
    wdir_uc_ucor_gnss          real,
    wdir_uc_ucor_sm            real,
    wdir_usm                   real,
    wmeri                      real,
    wmeri_corr_sm              real,
    wmeri_raw                  real,
    wmeri_raw_flags            real,
    wmeri_uc                   real,
    wmeri_uc_ucor              real,
    wmeri_uc_ucor_gnss         real,
    wmeri_uc_ucor_sm           real,
    wspeed                     real,
    wspeed_corr_sm             real,
    wspeed_uc                  real,
    wspeed_uc_ucor             real,
    wspeed_uc_ucor_gnss        real,
    wspeed_uc_ucor_sm          real,
    wspeed_usm                 real,
    wvmr_mass                  real,
    wvmr_mass_uc               real,
    wvmr_mass_uc_scor          real,
    wvmr_mass_uc_tcor          real,
    wvmr_mass_uc_ucor          real,
    wvmr_vol                   real,
    wvmr_vol_uc                real,
    wvmr_vol_uc_scor           real,
    wvmr_vol_uc_tcor           real,
    wvmr_vol_uc_ucor           real,
    wvpp                       real,
    wvpp_uc                    real,
    wvpp_uc_scor               real,
    wvpp_uc_tcor               real,
    wvpp_uc_ucor               real,
    wvsp                       real,
    wvsp_uc                    real,
    wvsp_uc_scor               real,
    wvsp_uc_tcor               real,
    wvsp_uc_ucor               real,
    wzon                       real,
    wzon_corr_sm               real,
    wzon_raw                   real,
    wzon_raw_flags             real,
    wzon_uc                    real,
    wzon_uc_ucor               real,
    wzon_uc_ucor_gnss          real,
    wzon_uc_ucor_sm            real,
    g_measurement_standardtime timestamp with time zone,
    idstation_pk               int
) PARTITION BY RANGE (g_measurement_standardtime);

-- Anonymous code block to create yearly partitions for RS41 data table
-- Creates partitions from 2014 (RS41 introduction) to 2025
DO
$$
    DECLARE
        start_date    date := '2014-01-01'::date;
        end_date      date := '2025-12-31'::date;
        step_date     date := start_date;
        interval_unit text := 'year';
    BEGIN
        -- Loop through each year from start_date to end_date
        WHILE step_date <= end_date
            LOOP
                -- Create partition for rs41_data table for current year
                PERFORM create_partition_table('rs41_data', step_date, interval_unit);

                -- Move to the next partition interval (increment by 1 year)
                step_date := date_trunc(interval_unit, step_date) + ('1 ' || interval_unit)::interval;
            END LOOP;
    END
$$;