-- Table: ims100_header
-- Purpose: Stores comprehensive header metadata for IMS100 radiosonde observations
-- Description: Contains detailed instrument metadata, station information, processing history,
--              and extensive ground check data for IMS100 radiosonde systems

DROP TABLE IF EXISTS ims100_header CASCADE;

CREATE TABLE ims100_header
(
    report_id                                           serial,
    conventions                                         character varying(255),
    title                                               character varying(255),
    institution                                         character varying(255),
    history                                             character varying(255),
    "references"                                          character varying(255),
    comment                                             character varying(255),
    g_product_id                                        character varying(255),
    g_product_key                                       character varying(255),
    g_product_name                                      character varying(255),
    g_product_version                                   character varying(255),
    g_product_level                                     character varying(255),
    g_product_leveldescription                          character varying(255),
    g_product_references                                character varying(255),
    g_product_history                                   character varying(255),
    g_product_producer                                  character varying(255),
    g_product_producertool                              character varying(255),
    g_product_producercontacat                          character varying(255),
    g_product_timeresolution                            character varying(255),
    g_product_status                                    character varying(255),
    g_product_statusdescription                         character varying(255),
    g_product_processingsteps                           text,
    g_product_prelaunchincluded                         character varying(255),
    g_product_ascentincluded                            character varying(255),
    g_product_descentincluded                           character varying(255),
    g_product_postflightincluded                        character varying(255),
    g_file_type                                         character varying(255),
    g_file_typeversion                                  character varying(255),
    g_file_typename                                     character varying(255),
    g_file_timestamp                                    timestamp with time zone,
    g_file_comment                                      character varying(255),
    g_site_id                                           character varying(255),
    g_site_key                                          character varying(255),
    g_site_name                                         character varying(255),
    g_site_latitude                                     real,
    g_site_longitude                                    real,
    g_site_altitude                                     real,
    g_measurementsystem_id                              character varying(255),
    g_measurementsystem_key                             character varying(255),
    g_measurementsystem_name                            character varying(255),
    g_measurementsystem_latitude                        real,
    g_measurementsystem_longitude                       real,
    g_measurementsystem_altitude                        real,
    g_measurementsystem_operatedby                      character varying(255),
    g_measurementsystem_wmocode                         character varying(255),
    g_measurementsystem_wmoname                         character varying(255),
    g_measurementsetup_id                               character varying(255),
    g_measurementsetup_key                              character varying(255),
    g_measurementsetup_name                             character varying(255),
    g_measurementsetup_type                             character varying(255),
    g_surfaceobs_pressure                               character varying(255),
    g_surfaceobs_temperature                            character varying(255),
    g_surfaceobs_relativehumidity                       character varying(255),
    g_surfaceobs_windspeed                              character varying(255),
    g_surfaceobs_winddirection                          character varying(255),
    g_measurement_id                                    character varying(255),
    g_measurement_lasechange                            character varying(255),
    g_measurement_standardtime                          timestamp with time zone,
    g_measurement_starttime                             timestamp with time zone,
    g_measurement_balloonnumber                         character varying(255),
    g_measurement_version                               character varying(255),
    g_measurement_equipment                             text,
    g_measurement_balloon                               character varying(255),
    g_measurement_fillingweight                         character varying(255),
    g_measurement_fillingvolume                         character varying(255),
    g_measurement_parachute                             character varying(255),
    g_measurement_unwinder                              character varying(255),
    g_measurement_fullstringlength                      character varying(255),
    g_measurement_rig                                   character varying(255),
    g_measurement_payload                               character varying(255),
    g_measurement_grossweight                           character varying(255),
    g_measurement_burstpointaltitude                    character varying(255),
    g_measurement_burstpointpressure                    character varying(255),
    g_measurement_burstpointgeopotheight                character varying(255),
    g_measurement_burstpointtime                        character varying(255),
    g_measurement_burstpointdatetime                    timestamp with time zone,
    g_measurement_precipitablewatercolumn               character varying(255),
    g_measurement_precipitablewatercolumnuc             character varying(255),
    g_measurement_tropopausegeopotheight                character varying(255),
    g_measurement_tropopausealtitude                    character varying(255),
    g_measurement_tropopausetemperature                 character varying(255),
    g_measurement_tropopausepressure                    character varying(255),
    g_measurement_tropopausepottemperature              character varying(255),
    g_measurement_tropopausetime                        character varying(255),
    g_measurement_tropopausedatetime                    character varying(255),
    g_measurement_lastchange                            timestamp with time zone,
    g_mainsonde_serialnumber                            character varying(255),
    g_mainsonde_model                                   character varying(255),
    g_mainsonde_name                                    character varying(255),
    g_mainsonde_modelfamily                             character varying(255),
    g_mainsonde_type                                    character varying(255),
    g_mainsonde_manufacturer                            character varying(255),
    g_telemetrysonde_serialnumber                       character varying(255),
    g_telemetrysonde_model                              character varying(255),
    g_telemetrysonde_name                               character varying(255),
    g_telemetrysonde_modelfamily                        character varying(255),
    g_telemetrysonde_type                               character varying(255),
    g_telemetrysonde_manufacturer                       character varying(255),
    g_groundsystem_id                                   character varying(255),
    g_groundsystem_model                                character varying(255),
    g_groundsystem_name                                 character varying(255),
    g_groundsystem_type                                 character varying(255),
    g_groundsystem_internalkey                          character varying(255),
    g_groundsystem_serialnumber                         character varying(255),
    g_groundsystem_manufacturer                         character varying(255),
    g_groundsystem_software                             character varying(255),
    g_groundcheck_list                                  character varying(255),
    g_groundcheck_rd08_gc_m2_001_checkdate              timestamp with time zone,
    g_groundcheck_rd08_gc_m2_001_checktype              character varying(255),
    g_groundcheck_rd08_gc_m2_001_checklength            character varying(255),
    g_groundcheck_rd08_gc_m2_001_reftemperature         character varying(255),
    g_groundcheck_rd08_gc_m2_001_refrelativehumidity    character varying(255),
    g_groundcheck_rd08_gc_m2_001_sensortemperature      character varying(255),
    g_groundcheck_rd08_gc_m2_001_sensorrelativehumidity character varying(255),
    g_groundcheck_shc_gc_16_001_checkdate               timestamp with time zone,
    g_groundcheck_shc_gc_16_001_checktype               character varying(255),
    g_groundcheck_shc_gc_16_001_checklength             character varying(255),
    g_groundcheck_shc_gc_16_001_reftemperature          character varying(255),
    g_groundcheck_shc_gc_16_001_refrelativehumidity     character varying(255),
    g_groundcheck_shc_gc_16_001_sensortemperature       character varying(255),
    g_groundcheck_shc_gc_16_001_sensorrelativehumidity  character varying(255),
    idstation_pk                                        int
);

-- Table: ims100_data
-- Purpose: Stores atmospheric measurement data from IMS100 radiosonde observations
-- Description: Contains comprehensive vertical profiles with extensive correction factors
--              and uncertainty estimates for temperature, humidity, pressure, wind,
--              and position measurements from IMS100 instruments

DROP TABLE IF EXISTS ims100_data CASCADE;

CREATE TABLE ims100_data
(
    observation_id                     serial,
    temp                               real,
    temp_corr                          real,
    temp_corr_spike_filtered           real,
    temp_uc_ucor_spike_filter          real,
    temp_corr_ma                       real,
    temp_uc_ucor_ma                    real,
    temp_corr_rad                      real,
    temp_corr_rad_heating              real,
    temp_corr_rad_orientation          real,
    temp_uc                            real,
    temp_uc_cor                        real,
    temp_uc_ucor                       real,
    temp_raw_flags                     int,
    temp_uc_cor_rad_corr_albedo        real,
    temp_uc_cor_rad_corr_vent          real,
    temp_uc_cor_calibration            real,
    temp_uc_cor_chamber                real,
    temp_uc_ucor_rad_corr_orientation  real,
    temp_flag_spike_filter             boolean,
    temp_flag_corr_rad                 boolean,
    rh                                 real,
    rh_corr                            real,
    rh_uc                              real,
    rh_uc_cor                          real,
    rh_uc_ucor                         real,
    rh_res                             real,
    rh_raw_flags                       int,
    negative_rh_flg                    boolean,
    rh_corr_tl                         real,
    rh_corr_contamination              real,
    rh_corr_hysteresis                 real,
    rh_corr_tud                        real,
    rh_corr_tsta                       real,
    rh_uc_cor_sensor_calib             real,
    rh_tl_corrected                    real,
    rh_uc_cor_tl_correction            real,
    rh_contamination_filtered          real,
    rh_uc_cor_contamination_filter     real,
    rh_uc_ucor_contamination_filter    real,
    rh_hysteresis_corrected            real,
    rh_uc_cor_hysteresis_correction    real,
    rh_uc_ucor_hysteresis_correction   real,
    rh_tud_corrected                   real,
    rh_uc_cor_tud_correction           real,
    rh_uc_ucor_tud_correction          real,
    rh_uc_cor_tsta_correction          real,
    rh_uc_ucor_tsta_correction         real,
    press                              real,
    press_uc                           real,
    press_uc_cor                       real,
    press_uc_ucor                      real,
    press_uc_cor_tv                    real,
    press_uc_psurf_cor                 real,
    press_uc_cor_height_from_rp        real,
    press_uc_ucor_tv                   real,
    press_uc_ucor_thickness            real,
    wzon                               real,
    wzon_uc                            real,
    wzon_uc_ucor                       real,
    wzon_uc_ucor_filter                real,
    wzon_raw_flags                     int,
    wmeri                              real,
    wmeri_uc                           real,
    wmeri_uc_ucor                      real,
    wmeri_uc_ucor_filter               real,
    wmeri_raw_flags                    int,
    wspeed                             real,
    wspeed_uc                          real,
    wspeed_uc_ucor                     real,
    wdir                               real,
    wdir_uc                            real,
    wdir_uc_ucor                       real,
    wzon_perturb                       real,
    wmeri_perturb                      real,
    wspeed_perturb                     real,
    wzon_mv                            real,
    wzon_mv_uc                         real,
    wzon_mv_uc_ucor                    real,
    wzon_mv_uc_ucor_filter             real,
    wzon_mv_raw_flags                  int,
    wmeri_mv                           real,
    wmeri_mv_uc                        real,
    wmeri_mv_uc_ucor                   real,
    wmeri_mv_uc_ucor_filter            real,
    wmeri_mv_raw_flags                 int,
    wspeed_mv                          real,
    wspeed_mv_uc                       real,
    wspeed_mv_uc_ucor                  real,
    wdir_mv                            real,
    wdir_mv_uc                         real,
    wdir_mv_uc_ucor                    real,
    wzon_mv_perturb                    real,
    wmeri_mv_perturb                   real,
    wspeed_mv_perturb                  real,
    wzon_ds                            real,
    wzon_ds_uc                         real,
    wzon_ds_uc_ucor                    real,
    wzon_ds_uc_ucor_filter             real,
    wzon_ds_raw_flags                  int,
    wmeri_ds                           real,
    wmeri_ds_uc                        real,
    wmeri_ds_uc_ucor                   real,
    wmeri_ds_uc_ucor_filter            real,
    wmeri_ds_raw_flags                 int,
    wspeed_ds                          real,
    wspeed_ds_uc                       real,
    wspeed_ds_uc_ucor                  real,
    wdir_ds                            real,
    wdir_ds_uc                         real,
    wdir_ds_uc_ucor                    real,
    wzon_ds_perturb                    real,
    wmeri_ds_perturb                   real,
    wspeed_ds_perturb                  real,
    alt_amsl                           real,
    alt_amsl_uc                        real,
    alt_amsl_uc_cor                    real,
    alt_amsl_uc_ucor                   real,
    alt_raw_flags                      int,
    alt_amsl_uc_cor_vdop               real,
    alt_amsl_uc_cor_release_transition real,
    alt_amsl_uc_cor_dac_timing         real,
    alt_amsl_uc_cor_geoid              real,
    alt_amsl_uc_ucor_ma                real,
    alt_flag_release_transition        boolean,
    alt_amsl_corr_release_transition   real,
    alt_amsl_corr_ma                   real,
    alt_gph                            real,
    alt_gph_uc_cor                     real,
    alt_gph_uc_ucor                    real,
    alt_gph_uc                         real,
    geoid                              real,
    geoid_corr                         real,
    alt_wgs84                          real,
    alt_wgs84_uc                       real,
    alt                                real,
    alt_uc                             real,
    vspeed_raw                         real,
    vspeed                             real,
    vspeed_uc                          real,
    lat                                real,
    lat_raw_flags                      int,
    lon                                real,
    lon_raw_flags                      int,
    fp                                 real,
    fp_uc                              real,
    mr_mass                            real,
    mr_mass_uc                         real,
    mr_vol                             real,
    mr_vol_uc                          real,
    wvpp_sat                           real,
    wvpp_sat_uc                        real,
    wvpp                               real,
    wvpp_uc                            real,
    thum                               real,
    thum_uc                            real,
    sea                                real,
    swdir                              real,
    vent                               real,
    vent_uc                            real,
    g_measurement_standardtime         timestamp with time zone,
    idstation_pk                       int
) PARTITION BY RANGE (g_measurement_standardtime);

-- Anonymous code block to create yearly partitions for IMS100 data table
-- Creates partitions from 2016 (IMS100 introduction) to 2025
DO
$$
    DECLARE
        start_date    date := '2016-01-01'::date;
        end_date      date := '2025-12-31'::date;
        step_date     date := start_date;
        interval_unit text := 'year';
    BEGIN
        -- Loop through each year from start_date to end_date
        WHILE step_date <= end_date
            LOOP
                -- Create partition for ims100_data table for current year
                PERFORM create_partition_table('ims100_data', step_date, interval_unit);

                -- Move to the next partition interval (increment by 1 year)
                step_date := date_trunc(interval_unit, step_date) + ('1 ' || interval_unit)::interval;
            END LOOP;
    END
$$;