DROP TABLE IF EXISTS header CASCADE;

CREATE TABLE header
(
    report_id                                           serial PRIMARY KEY,
    idstation_pk                                        int,
    report_timestamp                                    timestamp with time zone,
    
    -- Basic metadata
    conventions                                         character varying(255),
    title                                               character varying(255),
    institution                                         character varying(255),
    source                                              character varying(255),
    history                                             character varying(255),
    "references"                                        character varying(255),
    comment                                             character varying(255),
    
    -- File metadata
    g_file_type                                         character varying(255),
    g_file_typeversion                                  character varying(255),
    g_file_typename                                     character varying(255),
    g_file_timestamp                                    timestamp with time zone,
    g_file_comment                                      character varying(255),
    g_general_filetypeversion                           character varying(255),
    g_general_timestamp                                 timestamp with time zone,

    -- Site information
    g_site_id                                           character varying(255),
    g_site_key                                          character varying(255),
    g_site_name                                         character varying(255),
    g_site_latitude                                     real,
    g_site_longitude                                    real,
    g_site_altitude                                     real,
    g_site_country                                      character varying(255),
    g_site_district                                     character varying(255),
    g_site_institution                                  character varying(255),
    g_site_environmenttype                              character varying(255),
    g_site_landuse                                      character varying(255),
    g_site_topography                                   character varying(255),
    g_site_climate                                      character varying(255),
    g_site_population                                   character varying(255),
    g_site_surfaceroughness                             character varying(255),
    g_site_timezone                                     character varying(255),
    g_site_iscooperation                                character varying(255),
    g_site_isdistributed                                character varying(255),
    g_site_ismobile                                     character varying(255),
    g_general_sitecode                                  character varying(255),
    g_general_sitename                                  character varying(255),
    g_general_sitewmoid                                 character varying(255),
    g_general_siteinstitution                           character varying(255),

    -- Measurement system
    g_measurementsystem_id                              character varying(255),
    g_measurementsystem_key                             character varying(255),
    g_measurementsystem_name                            character varying(255),
    g_measurementsystem_latitude                        real,
    g_measurementsystem_longitude                       real,
    g_measurementsystem_altitude                        real,
    g_measurementsystem_operatedby                      character varying(255),
    g_measurementsystem_wmocode                         character varying(255),
    g_measurementsystem_wmoname                         character varying(255),
    g_measurementsystem_type                            character varying(255),
    g_measurementsystem_wigossid                        character varying(255),
    g_measurementsystem_wmoregion                       character varying(255),
    g_measuringsystem_id                                character varying(255),
    g_measuringsystem_latitude                          real,
    g_measuringsystem_longitude                         real,
    g_measuringsystem_altitude                          real,
    g_measuringsystem_type                              character varying(255),

    -- Measurement setup
    g_measurementsetup_id                               character varying(255),
    g_measurementsetup_key                              character varying(255),
    g_measurementsetup_name                             character varying(255),
    g_measurementsetup_type                             character varying(255),

    -- Surface observations
    g_surfaceobs_pressure                               character varying(255),
    g_surfaceobs_temperature                            character varying(255),
    g_surfaceobs_relativehumidity                       character varying(255),
    g_surfaceobs_windspeed                              character varying(255),
    g_surfaceobs_winddirection                          character varying(255),
    g_surfaceobs_cloudstext                             character varying(255),
    g_surfaceobs_synopclouds                            character varying(255),
    g_surfaceobs_comment                                character varying(255),

    -- Instrument metadata
    g_instrument_serialnumber                           character varying(255),
    g_instrument_type                                   character varying(255),
    g_instrument_typefamily                             character varying(255),
    g_instrument_manufacturer                           character varying(255),
    g_instrument_weight                                 character varying(255),
    g_instrument_telemetrysonde                         character varying(255),
    g_instrument_softwareversion                        character varying(255),
    g_instrument_comment                                character varying(255),

    -- Main sonde
    g_mainsonde_serialnumber                            character varying(255),
    g_mainsonde_model                                   character varying(255),
    g_mainsonde_name                                    character varying(255),
    g_mainsonde_modelfamily                             character varying(255),
    g_mainsonde_type                                    character varying(255),
    g_mainsonde_manufacturer                            character varying(255),

    -- Telemetry sonde
    g_telemetrysonde_serialnumber                       character varying(255),
    g_telemetrysonde_model                              character varying(255),
    g_telemetrysonde_name                               character varying(255),
    g_telemetrysonde_modelfamily                        character varying(255),
    g_telemetrysonde_type                               character varying(255),
    g_telemetrysonde_manufacturer                       character varying(255),
    g_telemetrysonde_xdata                              character varying(255),
    g_telemetrysonde_xdatasensors                       character varying(255),

    -- Ground system
    g_groundsystem_id                                   character varying(255),
    g_groundsystem_model                                character varying(255),
    g_groundsystem_name                                 character varying(255),
    g_groundsystem_type                                 character varying(255),
    g_groundsystem_internalkey                          character varying(255),
    g_groundsystem_serialnumber                         character varying(255),
    g_groundsystem_manufacturer                         character varying(255),
    g_groundsystem_software                             character varying(255),
    g_groundsystem_modelfamily                          character varying(255),

    -- Product metadata
    g_product_id                                        character varying(255),
    g_product_key                                       character varying(255),
    g_product_name                                      character varying(255),
    g_product_version                                   character varying(255),
    g_product_level                                     character varying(255),
    g_product_leveldescription                          character varying(255),
    g_product_references                                character varying(255),
    g_product_history                                   character varying(255),
    g_product_producer                                  character varying(255),
    g_product_producertool                              character varying(255),
    g_product_producercontacat                          character varying(255),
    g_product_timeresolution                            character varying(255),
    g_product_status                                    character varying(255),
    g_product_statusdescription                         character varying(255),
    g_product_processingsteps                           text,
    g_product_prelaunchincluded                         character varying(255),
    g_product_ascentincluded                            character varying(255),
    g_product_descentincluded                           character varying(255),
    g_product_postflightincluded                        character varying(255),
    g_product_code                                      character varying(255),
    g_product_orgresolution                             character varying(255),
    g_product_processingcode                            character varying(255),
    g_product_fullkey                                   character varying(255),
    g_product_revision                                  character varying(255),
    g_product_title                                     character varying(255),
    g_product_description                               character varying(255),

    -- Measurement/Ascent data
    g_measurement_id                                    character varying(255),
    g_measurement_lasechange                            character varying(255),
    g_measurement_standardtime                          timestamp with time zone,
    g_measurement_starttime                             timestamp with time zone,
    g_measurement_balloonnumber                         character varying(255),
    g_measurement_version                               character varying(255),
    g_measurement_equipment                             text,
    g_measurement_balloon                               character varying(255),
    g_measurement_fillingweight                         character varying(255),
    g_measurement_fillingvolume                         character varying(255),
    g_measurement_parachute                             character varying(255),
    g_measurement_unwinder                              character varying(255),
    g_measurement_fullstringlength                      character varying(255),
    g_measurement_rig                                   character varying(255),
    g_measurement_payload                               character varying(255),
    g_measurement_grossweight                           character varying(255),
    g_measurement_burstpointaltitude                    character varying(255),
    g_measurement_burstpointpressure                    character varying(255),
    g_measurement_burstpointgeopotheight                character varying(255),
    g_measurement_burstpointtime                        character varying(255),
    g_measurement_burstpointdatetime                    timestamp with time zone,
    g_measurement_precipitablewatercolumn               character varying(255),
    g_measurement_precipitablewatercolumnuc             character varying(255),
    g_measurement_tropopausegeopotheight                character varying(255),
    g_measurement_tropopausealtitude                    character varying(255),
    g_measurement_tropopausetemperature                 character varying(255),
    g_measurement_tropopausepressure                    character varying(255),
    g_measurement_tropopausepottemperature              character varying(255),
    g_measurement_tropopausetime                        character varying(255),
    g_measurement_tropopausedatetime                    character varying(255),
    g_measurement_lastchange                            timestamp with time zone,
    g_measurement_internalkey                           character varying(255),
    g_measurement_locgpsaltitudegeoid                   character varying(255),
    g_measurement_locgpsaltitudemean                    character varying(255),
    g_measurement_locgpsaltitudeoffset                  character varying(255),
    g_measurement_locgpsaltituderef                     character varying(255),
    g_measurement_locgpsaltituderesidual                character varying(255),
    g_measurement_astronomicaltwilightcount             character varying(255),
    g_measurement_civiltwilightcount                    character varying(255),
    g_measurement_daytimecount                          character varying(255),
    g_measurement_nauticaltwilightcount                 character varying(255),
    g_measurement_nighttimecount                        character varying(255),
    g_measurement_partlyvisiblesuncount                 character varying(255),
    g_measurement_positionrangelatnorth                 character varying(255),
    g_measurement_positionrangelatsouth                 character varying(255),
    g_measurement_positionrangeloneast                  character varying(255),
    g_measurement_positionrangelonwest                  character varying(255),
    g_measurement_starttimediff                         character varying(255),
    g_measurement_starttimemanufacturer                 character varying(255),
    g_measurement_starttimesource                       character varying(255),
    g_measurement_timeofday                             character varying(255),
    g_measurement_tropopausedetected                    character varying(255),
    g_measurement_twilightcount                         character varying(255),
    g_measurement_burstpointsource                      character varying(255),

    -- Ascent specific fields
    g_ascent_id                                         character varying(255),
    g_ascent_standardtime                               timestamp with time zone,
    g_ascent_starttime                                  timestamp with time zone,
    g_ascent_balloonnumber                              character varying(255),
    g_ascent_balloontype                                character varying(255),
    g_ascent_unwindertype                               character varying(255),
    g_ascent_fillingweight                              character varying(255),
    g_ascent_payload                                    character varying(255),
    g_ascent_grossweight                                character varying(255),
    g_ascent_includedescent                             character varying(255),
    g_ascent_burstpointaltitude                         character varying(255),
    g_ascent_burstpointpressure                         character varying(255),
    g_ascent_tropopauseheight                           character varying(255),
    g_ascent_tropopausetemperature                      character varying(255),
    g_ascent_tropopausepressure                         character varying(255),
    g_ascent_tropopausepottemperature                   character varying(255),
    g_ascent_precipitablewatercolumn                    character varying(255),
    g_ascent_precipitablewatercolumnu                   character varying(255),
    g_ascent_comment                                    character varying(255),
    
    -- Ground check data
    g_groundcheck_list                                  character varying(255),
    
    -- RD08 ground check
    g_groundcheck_rd08_gc_m2_001_checkdate              timestamp with time zone,
    g_groundcheck_rd08_gc_m2_001_checktype              character varying(255),
    g_groundcheck_rd08_gc_m2_001_checklength            character varying(255),
    g_groundcheck_rd08_gc_m2_001_reftemperature         character varying(255),
    g_groundcheck_rd08_gc_m2_001_refrelativehumidity    character varying(255),
    g_groundcheck_rd08_gc_m2_001_sensortemperature      character varying(255),
    g_groundcheck_rd08_gc_m2_001_sensorrelativehumidity character varying(255),
    
    -- SHC ground check
    g_groundcheck_shc_gc_16_001_checkdate               timestamp with time zone,
    g_groundcheck_shc_gc_16_001_checktype               character varying(255),
    g_groundcheck_shc_gc_16_001_checklength             character varying(255),
    g_groundcheck_shc_gc_16_001_reftemperature          character varying(255),
    g_groundcheck_shc_gc_16_001_refrelativehumidity     character varying(255),
    g_groundcheck_shc_gc_16_001_sensortemperature       character varying(255),
    g_groundcheck_shc_gc_16_001_sensorrelativehumidity  character varying(255),
    
    -- RI41 ground check
    g_groundcheck_ri41_altitude                         character varying(255),
    g_groundcheck_ri41_available                        character varying(255),
    g_groundcheck_ri41_checkdate                        character varying(255),
    g_groundcheck_ri41_checklength                      character varying(255),
    g_groundcheck_ri41_checktype                        character varying(255),
    g_groundcheck_ri41_offsetaltituderefpressure        character varying(255),
    g_groundcheck_ri41_offsetpressure                   character varying(255),
    g_groundcheck_ri41_pressureqc                       character varying(255),
    g_groundcheck_ri41_refpressure                      character varying(255),
    g_groundcheck_ri41_sensorpressure                   character varying(255),
    
    -- SHC ground check
    g_groundcheck_shc_altitude                          character varying(255),
    g_groundcheck_shc_analysed                          character varying(255),
    g_groundcheck_shc_autodetected                      character varying(255),
    g_groundcheck_shc_available                         character varying(255),
    g_groundcheck_shc_checkdate                         character varying(255),
    g_groundcheck_shc_checklength                       character varying(255),
    g_groundcheck_shc_checktype                         character varying(255),
    g_groundcheck_shc_offsetaltituderefpressure         character varying(255),
    g_groundcheck_shc_offsetpressure                    character varying(255),
    g_groundcheck_shc_offsetpressureuc                  character varying(255),
    g_groundcheck_shc_offsetrelativehumidity            character varying(255),
    g_groundcheck_shc_offsetrelativehumidityuc          character varying(255),
    g_groundcheck_shc_offsettemperature                 character varying(255),
    g_groundcheck_shc_offsettemperatureuc               character varying(255),
    g_groundcheck_shc_pressureqc                        character varying(255),
    g_groundcheck_shc_refpressure                       character varying(255),
    g_groundcheck_shc_refpressurecount                  character varying(255),
    g_groundcheck_shc_refpressurelinslope               character varying(255),
    g_groundcheck_shc_refpressurestddev                 character varying(255),
    g_groundcheck_shc_refpressureuc                     character varying(255),
    g_groundcheck_shc_refpressureucfinal                character varying(255),
    g_groundcheck_shc_refrelativehumidity               character varying(255),
    g_groundcheck_shc_refrelativehumiditycount          character varying(255),
    g_groundcheck_shc_refrelativehumiditylinslope       character varying(255),
    g_groundcheck_shc_refrelativehumiditystddev         character varying(255),
    g_groundcheck_shc_refrelativehumidityuc             character varying(255),
    g_groundcheck_shc_refrelativehumidityucfinal        character varying(255),
    g_groundcheck_shc_reftemperature                    character varying(255),
    g_groundcheck_shc_reftemperaturecount               character varying(255),
    g_groundcheck_shc_reftemperaturelinslope            character varying(255),
    g_groundcheck_shc_reftemperaturestddev              character varying(255),
    g_groundcheck_shc_reftemperatureuc                  character varying(255),
    g_groundcheck_shc_reftemperatureucfinal             character varying(255),
    g_groundcheck_shc_relativehumidityqc                character varying(255),
    g_groundcheck_shc_relativehumiditysensorsdiff       character varying(255),
    g_groundcheck_shc_relativehumiditysensorsqc         character varying(255),
    g_groundcheck_shc_sensorpressure                    character varying(255),
    g_groundcheck_shc_sensorpressurecount               character varying(255),
    g_groundcheck_shc_sensorpressurelinslope            character varying(255),
    g_groundcheck_shc_sensorpressurestddev              character varying(255),
    g_groundcheck_shc_sensorpressureuc                  character varying(255),
    g_groundcheck_shc_sensorpressureucfinal             character varying(255),
    g_groundcheck_shc_sensorrelativehumidity            character varying(255),
    g_groundcheck_shc_sensorrelativehumiditycount       character varying(255),
    g_groundcheck_shc_sensorrelativehumiditylinslope    character varying(255),
    g_groundcheck_shc_sensorrelativehumiditystddev      character varying(255),
    g_groundcheck_shc_sensorrelativehumidityuc          character varying(255),
    g_groundcheck_shc_sensorrelativehumidityucfinal     character varying(255),
    g_groundcheck_shc_sensortemperature                 character varying(255),
    g_groundcheck_shc_sensortemperaturecount            character varying(255),
    g_groundcheck_shc_sensortemperaturelinslope         character varying(255),
    g_groundcheck_shc_sensortemperaturestddev           character varying(255),
    g_groundcheck_shc_sensortemperatureuc               character varying(255),
    g_groundcheck_shc_sensortemperatureucfinal          character varying(255),
    g_groundcheck_shc_temperatureqc                     character varying(255),
    g_groundcheck_shelter_available                     character varying(255)
);