DROP TABLE IF EXISTS data CASCADE;

CREATE TABLE data
(
    -- Common identifier
    observation_id                     serial,
    idstation_pk                       int,

    -- Timestamps
--     g_measurement_standardtime         timestamp with time zone,
--     g_ascent_standardtime              timestamp with time zone,
    report_timestamp                   timestamp with time zone,

    -- Position and coordinates
    lat                                real,
    lat_raw_flags                      int,
    lat_sm                             double precision,
    lat_uc                             real,
    lat_uc_tcor                        real,
    lat_uc_ucor                        real,
    latmf                              double precision,
    lon                                real,
    lon_raw_flags                      int,
    lon_sm                             double precision,
    lon_uc                             real,
    lon_uc_tcor                        real,
    lon_uc_ucor                        real,
    lonmf                              double precision,
    posx_raw                           double precision,
    posx_raw_flags                     real,
    posy_raw                           double precision,
    posy_raw_flags                     real,
    posz_raw                           double precision,
    posz_raw_flags                     real,

    -- Altitude and height measurements
    alt                                real,
    alt_uc                             real,
    alt_amsl                           real,
    alt_amsl_uc                        real,
    alt_amsl_uc_cor                    real,
    alt_amsl_uc_ucor                   real,
    alt_raw_flags                      int,
    alt_amsl_uc_cor_vdop               real,
    alt_amsl_uc_cor_release_transition real,
    alt_amsl_uc_cor_dac_timing         real,
    alt_amsl_uc_cor_geoid              real,
    alt_amsl_uc_ucor_ma                real,
    alt_flag_release_transition        boolean,
    alt_amsl_corr_release_transition   real,
    alt_amsl_corr_ma                   real,
    alt_gph                            real,
    alt_gph_uc_cor                     real,
    alt_gph_uc_ucor                    real,
    alt_gph_uc                         real,
    alt_wgs84                          real,
    alt_wgs84_uc                       real,
    geoid                              real,
    geoid_corr                         real,

    -- Temperature measurements
    temp                               real,
    temp_corr                          real,
    temp_corr_spike_filtered           real,
    temp_uc_ucor_spike_filter          real,
    temp_corr_ma                       real,
    temp_uc_ucor_ma                    real,
    temp_corr_rad                      real,
    temp_corr_rad_heating              real,
    temp_corr_rad_orientation          real,
    temp_uc                            real,
    temp_uc_cor                        real,
    temp_uc_ucor                       real,
    temp_uc_cor_rad_corr_albedo        real,
    temp_uc_cor_rad_corr_vent          real,
    temp_uc_cor_calibration            real,
    temp_uc_cor_chamber                real,
    temp_uc_ucor_rad_corr_orientation  real,
    temp_flag_spike_filter             boolean,
    temp_flag_corr_rad                 boolean,
    temp_corr_sm                       real,
    temp_raw                           real,
    temp_raw_flags                     real,
    temp_res                           real,
    temp_uc_rad                        real,
    temp_uc_scor                       real,
    temp_uc_scor_rad                   real,
    temp_uc_tcor                       real,
    temp_uc_tcor_cal                   real,
    temp_uc_tcor_rad                   real,
    temp_uc_ucor_rad                   real,
    temp_uc_ucor_sm                    real,

    -- Humidity measurements
    rh                                 real,
    rh_corr                            real,
    rh_uc                              real,
    rh_uc_cor                          real,
    rh_uc_ucor                         real,
    rh_res                             real,
    negative_rh_flg                    boolean,
    rh_corr_tl                         real,
    rh_corr_contamination              real,
    rh_corr_hysteresis                 real,
    rh_corr_tud                        real,
    rh_corr_tsta                       real,
    rh_uc_cor_sensor_calib             real,
    rh_tl_corrected                    real,
    rh_uc_cor_tl_correction            real,
    rh_contamination_filtered          real,
    rh_uc_cor_contamination_filter     real,
    rh_uc_ucor_contamination_filter    real,
    rh_hysteresis_corrected            real,
    rh_uc_cor_hysteresis_correction    real,
    rh_uc_ucor_hysteresis_correction   real,
    rh_tud_corrected                   real,
    rh_uc_cor_tud_correction           real,
    rh_uc_ucor_tud_correction          real,
    rh_uc_cor_tsta_correction          real,
    rh_uc_ucor_tsta_correction         real,
    rh_corr_sm                         real,
    rh_corr_trc                        real,
    rh_raw                             real,
    rh_raw_flags                       real,
    rh_uc_tcor                         real,
    rh_uc_tcor_cal                     real,
    rh_uc_tcor_tint                    real,
    rh_uc_tcor_tlc                     real,
    rh_uc_tlc                          real,
    rh_uc_ucor_sm                      real,
    rh_uc_ucor_tair                    real,
    rh_uc_ucor_tlc                     real,

    -- Pressure measurements
    press                              real,
    press_uc                           real,
    press_uc_cor                       real,
    press_uc_ucor                      real,
    press_uc_cor_tv                    real,
    press_uc_psurf_cor                 real,
    press_uc_cor_height_from_rp        real,
    press_uc_ucor_tv                   real,
    press_uc_ucor_thickness            real,
    press_gnss                         real,
    press_gnss_uc                      real,
    press_gnss_uc_tcor                 real,
    press_gnss_uc_ucor                 real,
    press_sens                         real,
    press_sens_corr                    real,
    press_sens_corr_cal                real,
    press_sens_corr_sm                 real,
    press_sens_raw                     real,
    press_sens_raw_flags               real,
    press_sens_uc                      real,
    press_sens_uc_tcor                 real,
    press_sens_uc_tcor_cal             real,
    press_sens_uc_ucor                 real,
    press_sens_uc_ucor_sm              real,

    -- Wind measurements (main)
    wzon                               real,
    wzon_uc                            real,
    wzon_uc_ucor                       real,
    wzon_uc_ucor_filter                real,
    wmeri                              real,
    wmeri_uc                           real,
    wmeri_uc_ucor                      real,
    wmeri_uc_ucor_filter               real,
    wspeed                             real,
    wspeed_uc                          real,
    wspeed_uc_ucor                     real,
    wdir                               real,
    wdir_uc                            real,
    wdir_uc_ucor                       real,
    wzon_perturb                       real,
    wmeri_perturb                      real,
    wspeed_perturb                     real,

    -- Wind measurements (MV)
    wzon_mv                            real,
    wzon_mv_uc                         real,
    wzon_mv_uc_ucor                    real,
    wzon_mv_uc_ucor_filter             real,
    wzon_mv_raw_flags                  int,
    wmeri_mv                           real,
    wmeri_mv_uc                        real,
    wmeri_mv_uc_ucor                   real,
    wmeri_mv_uc_ucor_filter            real,
    wmeri_mv_raw_flags                 int,
    wspeed_mv                          real,
    wspeed_mv_uc                       real,
    wspeed_mv_uc_ucor                  real,
    wdir_mv                            real,
    wdir_mv_uc                         real,
    wdir_mv_uc_ucor                    real,
    wzon_mv_perturb                    real,
    wmeri_mv_perturb                   real,
    wspeed_mv_perturb                  real,

    -- Wind measurements (DS)
    wzon_ds                            real,
    wzon_ds_uc                         real,
    wzon_ds_uc_ucor                    real,
    wzon_ds_uc_ucor_filter             real,
    wzon_ds_raw_flags                  int,
    wmeri_ds                           real,
    wmeri_ds_uc                        real,
    wmeri_ds_uc_ucor                   real,
    wmeri_ds_uc_ucor_filter            real,
    wmeri_ds_raw_flags                 int,
    wspeed_ds                          real,
    wspeed_ds_uc                       real,
    wspeed_ds_uc_ucor                  real,
    wdir_ds                            real,
    wdir_ds_uc                         real,
    wdir_ds_uc_ucor                    real,
    wzon_ds_perturb                    real,
    wmeri_ds_perturb                   real,
    wspeed_ds_perturb                  real,

    -- Additional wind corrected/smoothed
    wzon_corr_sm                       real,
    wzon_raw                           real,
    wzon_raw_flags                     real,
    wzon_uc_ucor_gnss                  real,
    wzon_uc_ucor_sm                    real,
    wmeri_corr_sm                      real,
    wmeri_raw                          real,
    wmeri_raw_flags                    real,
    wmeri_uc_ucor_gnss                 real,
    wmeri_uc_ucor_sm                   real,
    wspeed_corr_sm                     real,
    wspeed_uc_ucor_gnss                real,
    wspeed_uc_ucor_sm                  real,
    wdir_corr_sm                       real,
    wdir_uc_ucor_gnss                  real,
    wdir_uc_ucor_sm                    real,
    wdir_usm                           real,
    wspeed_usm                         real,

    -- Vertical speed
    vspeed_raw                         real,
    vspeed                             real,
    vspeed_uc                          real,

    -- Moisture and water vapor
    fp                                 real,
    fp_uc                              real,
    mr_mass                            real,
    mr_mass_uc                         real,
    mr_vol                             real,
    mr_vol_uc                          real,
    wvpp_sat                           real,
    wvpp_sat_uc                        real,
    wvpp                               real,
    wvpp_uc                            real,
    wvpp_uc_scor                       real,
    wvpp_uc_tcor                       real,
    wvpp_uc_ucor                       real,
    wvmr_mass                          real,
    wvmr_mass_uc                       real,
    wvmr_mass_uc_scor                  real,
    wvmr_mass_uc_tcor                  real,
    wvmr_mass_uc_ucor                  real,
    wvmr_vol                           real,
    wvmr_vol_uc                        real,
    wvmr_vol_uc_scor                   real,
    wvmr_vol_uc_tcor                   real,
    wvmr_vol_uc_ucor                   real,
    wvsp                               real,
    wvsp_uc                            real,
    wvsp_uc_scor                       real,
    wvsp_uc_tcor                       real,
    wvsp_uc_ucor                       real,

    -- Radiation and solar
    swdir                              real,
    swdir_uc                           real,
    swdir_uc_scor                      real,
    swdif                              real,
    swdif_uc                           real,
    swdif_uc_scor                      real,
    swrad                              real,
    penper                             real,
    penrad                             real,
    penrad_uc                          real,
    penrad_uc_ucor                     real,
    penspeed                           real,
    penspeed_uc                        real,
    penspeed_uc_ucor                   real,
    sza                                real,
    saa                                real,

    -- Miscellaneous measurements
    thum                               real,
    thum_uc                            real,
    thum_raw                           real,
    thum_raw_flags                     real,
    sea                                real,
    vent                               real,
    vent_uc                            real,
    band                               real,
    ciwv                               real,
    ciwv_uc                            real,
    dorn                               real,
    dp                                 real,
    dp_uc                              real,
    dp_uc_scor                         real,
    dp_uc_tcor                         real,
    dp_uc_ucor                         real,
    grav                               real,
    hca                                real,
    hdop_raw                           real,
    icesat                             real,
    ihum_raw                           real,
    ihum_raw_flags                     real,
    tau_rh                             real,
    tau_rh_uc                          real,
    tau_rh_uc_tcor                     real,
    vdop_raw                           real,

    -- Combined/corrected variables
    "asc"                              real,
    cor_rh                             real,
    cor_temp                           real,
    geopot                             real,
    wvmr                               real,

    -- Uncertainty fields
    u_alt                              real,
    u_cor_rh                           real,
    u_cor_temp                         real,
    u_press                            real,
    u_rh                               real,
    u_std_rh                           real,
    u_std_temp                         real,
    u_swrad                            real,
    u_temp                             real,
    u_wdir                             real,
    u_wspeed                           real

) PARTITION BY RANGE (report_timestamp);

DO
$$
    DECLARE
        start_date    date := '2004-01-01'::date;
        end_date      date := '2025-12-31'::date;
        step_date     date := start_date;
        interval_unit text := 'year';
    BEGIN
        -- Loop through each year from start_date to end_date
        WHILE step_date <= end_date
            LOOP
                -- Create partition for radiosonde_data table for current year
                PERFORM create_partition_table('data', step_date, interval_unit);

                -- Move to the next partition interval (increment by 1 year)
                step_date := date_trunc(interval_unit, step_date) + ('1 ' || interval_unit)::interval;
            END LOOP;
    END
$$;